[package]
name = "jsonrpsee-server"
description = "JSON-RPC server that supports HTTP and WebSocket transports"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
readme.workspace = true
publish = true

[dependencies]
async-trait = "0.1.73"
futures-util = { version = "0.3.14", default-features = false, features = ["io", "async-await-macro"] }
jsonrpsee-types = { workspace = true }
jsonrpsee-core = { workspace = true, features = ["server", "soketto", "http-helpers"] }
tracing = "0.1.34"
serde = "1"
serde_json = { version = "1", features = ["raw_value"] }
soketto = { version = "0.7.1", features = ["http"] }
tokio = { version = "1.16", features = ["net", "rt-multi-thread", "macros", "time"] }
tokio-util = { version = "0.7", features = ["compat"] }
tokio-stream = "0.1.7"
hyper = { version = "0.14", features = ["server", "http1", "http2"] }
tower = { version = "0.4.13", features = ["util"] }
route-recognizer = "0.3.1"
http = "0.2.9"
thiserror = "1.0.44"

[dev-dependencies]
anyhow = "1"
jsonrpsee-test-utils = { path = "../test-utils" }
rand = "0.8"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
tower = { version = "0.4.13", features = ["timeout"] }
socket2 = "0.5.1"
